// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_GST_REQUEST = "INSERT_GST_REQUEST";
export const INSERT_GST_SUCCESS = "INSERT_GST_SUCCESS";
export const INSERT_GST_FAILURE = "INSERT_GST_FAILURE";
export const FIND_GST_BY_ID_REQUEST = "FIND_GST_BY_ID_REQUEST";
export const FIND_GST_BY_ID_SUCCESS = "FIND_GST_BY_ID_SUCCESS";
export const FIND_GST_BY_ID_FAILURE = "FIND_GST_BY_ID_FAILURE";
export const FIND_ALL_GST_REQUEST = "FIND_ALL_GST_REQUEST";
export const FIND_ALL_GST_SUCCESS = "FIND_ALL_GST_SUCCESS";
export const FIND_ALL_GST_FAILURE = "FIND_ALL_GST_FAILURE";
export const UPDATE_GST_REQUEST = "UPDATE_GST_REQUEST";
export const UPDATE_GST_SUCCESS = "UPDATE_GST_SUCCESS";
export const UPDATE_GST_FAILURE = "UPDATE_GST_FAILURE";
export const DELETE_GST_REQUEST = "DELETE_GST_REQUEST";
export const DELETE_GST_SUCCESS = "DELETE_GST_SUCCESS";
export const DELETE_GST_FAILURE = "DELETE_GST_FAILURE";
export const DELETE_GST_PERMANENTLY_REQUEST = "DELETE_GST_PERMANENTLY_REQUEST";
export const DELETE_GST_PERMANENTLY_SUCCESS = "DELETE_GST_PERMANENTLY_SUCCESS";
export const DELETE_GST_PERMANENTLY_FAILURE = "DELETE_GST_PERMANENTLY_FAILURE";
