// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_WORK_REQUEST = "INSERT_WORK_REQUEST";
export const INSERT_WORK_SUCCESS = "INSERT_WORK_SUCCESS";
export const INSERT_WORK_FAILURE = "INSERT_WORK_FAILURE";
export const FIND_WORK_BY_ID_REQUEST = "FIND_WORK_BY_ID_REQUEST";
export const FIND_WORK_BY_ID_SUCCESS = "FIND_WORK_BY_ID_SUCCESS";
export const FIND_WORK_BY_ID_FAILURE = "FIND_WORK_BY_ID_FAILURE";
export const FIND_ALL_WORKS_REQUEST = "FIND_ALL_WORKS_REQUEST";
export const FIND_ALL_WORKS_SUCCESS = "FIND_ALL_WORKS_SUCCESS";
export const FIND_ALL_WORKS_FAILURE = "FIND_ALL_WORKS_FAILURE";
export const FIND_WORK_BY_NAME_REQUEST = "FIND_WORK_BY_NAME_REQUEST";
export const FIND_WORK_BY_NAME_SUCCESS = "FIND_WORK_BY_NAME_SUCCESS";
export const FIND_WORK_BY_NAME_FAILURE = "FIND_WORK_BY_NAME_FAILURE";
export const UPDATE_WORK_REQUEST = "UPDATE_WORK_REQUEST";
export const UPDATE_WORK_SUCCESS = "UPDATE_WORK_SUCCESS";
export const UPDATE_WORK_FAILURE = "UPDATE_WORK_FAILURE";
export const DELETE_WORK_REQUEST = "DELETE_WORK_REQUEST";
export const DELETE_WORK_SUCCESS = "DELETE_WORK_SUCCESS";
export const DELETE_WORK_FAILURE = "DELETE_WORK_FAILURE";
export const DELETE_WORK_PERMANENTLY_REQUEST =
  "DELETE_WORK_PERMANENTLY_REQUEST";
export const DELETE_WORK_PERMANENTLY_SUCCESS =
  "DELETE_WORK_PERMANENTLY_SUCCESS";
export const DELETE_WORK_PERMANENTLY_FAILURE =
  "DELETE_WORK_PERMANENTLY_FAILURE";
