// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_BOQ_REQUEST = "INSERT_BOQ_REQUEST";
export const INSERT_BOQ_SUCCESS = "INSERT_BOQ_SUCCESS";
export const INSERT_BOQ_FAILURE = "INSERT_BOQ_FAILURE";
export const FIND_BOQ_BY_ID_REQUEST = "FIND_BOQ_BY_ID_REQUEST";
export const FIND_BOQ_BY_ID_SUCCESS = "FIND_BOQ_BY_ID_SUCCESS";
export const FIND_BOQ_BY_ID_FAILURE = "FIND_BOQ_BY_ID_FAILURE";
export const FIND_BOQ_BY_BOQID_REQUEST = "FIND_BOQ_BY_BOQID_REQUEST";
export const FIND_BOQ_BY_BOQID_SUCCESS = "FIND_BOQ_BY_BOQID_SUCCESS";
export const FIND_BOQ_BY_BOQID_FAILURE = "FIND_BOQ_BY_BOQID_FAILURE";
export const FIND_ALL_BOQS_REQUEST = "FIND_ALL_BOQS_REQUEST";
export const FIND_ALL_BOQS_SUCCESS = "FIND_ALL_BOQS_SUCCESS";
export const FIND_ALL_BOQS_FAILURE = "FIND_ALL_BOQS_FAILURE";
export const UPDATE_BOQ_REQUEST = "UPDATE_BOQ_REQUEST";
export const UPDATE_BOQ_SUCCESS = "UPDATE_BOQ_SUCCESS";
export const UPDATE_BOQ_FAILURE = "UPDATE_BOQ_FAILURE";
export const DELETE_BOQ_REQUEST = "DELETE_BOQ_REQUEST";
export const DELETE_BOQ_SUCCESS = "DELETE_BOQ_SUCCESS";
export const DELETE_BOQ_FAILURE = "DELETE_BOQ_FAILURE";
export const DELETE_BOQ_PERMANENTLY_REQUEST = "DELETE_BOQ_PERMANENTLY_REQUEST";
export const DELETE_BOQ_PERMANENTLY_SUCCESS = "DELETE_BOQ_PERMANENTLY_SUCCESS";
export const DELETE_BOQ_PERMANENTLY_FAILURE = "DELETE_BOQ_PERMANENTLY_FAILURE";
