// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_DEPARTMENT_REQUEST = "INSERT_DEPARTMENT_REQUEST";
export const INSERT_DEPARTMENT_SUCCESS = "INSERT_DEPARTMENT_SUCCESS";
export const INSERT_DEPARTMENT_FAILURE = "INSERT_DEPARTMENT_FAILURE";
export const FIND_DEPARTMENT_BY_ID_REQUEST = "FIND_DEPARTMENT_BY_ID_REQUEST";
export const FIND_DEPARTMENT_BY_ID_SUCCESS = "FIND_DEPARTMENT_BY_ID_SUCCESS";
export const FIND_DEPARTMENT_BY_ID_FAILURE = "FIND_DEPARTMENT_BY_ID_FAILURE";
export const FIND_ALL_DEPARTMENTS_REQUEST = "FIND_ALL_DEPARTMENTS_REQUEST";
export const FIND_ALL_DEPARTMENTS_SUCCESS = "FIND_ALL_DEPARTMENTS_SUCCESS";
export const FIND_ALL_DEPARTMENTS_FAILURE = "FIND_ALL_DEPARTMENTS_FAILURE";
export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";
export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILURE = "DELETE_DEPARTMENT_FAILURE";
export const DELETE_DEPARTMENT_PERMANENTLY_REQUEST =
  "DELETE_DEPARTMENT_PERMANENTLY_REQUEST";
export const DELETE_DEPARTMENT_PERMANENTLY_SUCCESS =
  "DELETE_DEPARTMENT_PERMANENTLY_SUCCESS";
export const DELETE_DEPARTMENT_PERMANENTLY_FAILURE =
  "DELETE_DEPARTMENT_PERMANENTLY_FAILURE";
