// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_MACHINE_SUCCESS = "INSERT_MACHINE_SUCCESS";
export const INSERT_MACHINE_FAILURE = "INSERT_MACHINE_FAILURE";
export const INSERT_MACHINE_REQUEST = "INSERT_MACHINE_REQUEST";
export const FIND_MACHINE_BY_ID_REQUEST = "FIND_MACHINE_BY_ID_REQUEST";
export const FIND_MACHINE_BY_ID_SUCCESS = "FIND_MACHINE_BY_ID_SUCCESS";
export const FIND_MACHINE_BY_ID_FAILURE = "FIND_MACHINE_BY_ID_FAILURE";
export const FIND_ALL_MACHINES_REQUEST = "FIND_ALL_MACHINES_REQUEST";
export const FIND_ALL_MACHINES_SUCCESS = "FIND_ALL_MACHINES_SUCCESS";
export const FIND_ALL_MACHINES_FAILURE = "FIND_ALL_MACHINES_FAILURE";
export const FIND_MACHINE_BY_NAME_REQUEST = "FIND_MACHINE_BY_NAME_REQUEST";
export const FIND_MACHINE_BY_NAME_SUCCESS = "FIND_MACHINE_BY_NAME_SUCCESS";
export const FIND_MACHINE_BY_NAME_FAILURE = "FIND_MACHINE_BY_NAME_FAILURE";
export const UPDATE_MACHINE_REQUEST = "UPDATE_MACHINE_REQUEST";
export const UPDATE_MACHINE_SUCCESS = "UPDATE_MACHINE_SUCCESS";
export const UPDATE_MACHINE_FAILURE = "UPDATE_MACHINE_FAILURE";
export const DELETE_MACHINE_REQUEST = "DELETE_MACHINE_REQUEST";
export const DELETE_MACHINE_SUCCESS = "DELETE_MACHINE_SUCCESS";
export const DELETE_MACHINE_FAILURE = "DELETE_MACHINE_FAILURE";
export const DELETE_MACHINE_PERMANENTLY_REQUEST =
  "DELETE_MACHINE_PERMANENTLY_REQUEST";
export const DELETE_MACHINE_PERMANENTLY_SUCCESS =
  "DELETE_MACHINE_PERMANENTLY_SUCCESS";
export const DELETE_MACHINE_PERMANENTLY_FAILURE =
  "DELETE_MACHINE_PERMANENTLY_FAILURE";
