// Author: Ashutosh Rao Chawan & Suggala Manasvi
export const INSERT_TEMPLATE_SUCCESS = "INSERT_TEMPLATE_SUCCESS";
export const INSERT_TEMPLATE_FAILURE = "INSERT_TEMPLATE_FAILURE";
export const INSERT_TEMPLATE_REQUEST = "INSERT_TEMPLATE_REQUEST";
export const FIND_TEMPLATE_BY_ID_REQUEST = "FIND_TEMPLATE_BY_ID_REQUEST";
export const FIND_TEMPLATE_BY_ID_SUCCESS = "FIND_TEMPLATE_BY_ID_SUCCESS";
export const FIND_TEMPLATE_BY_ID_FAILURE = "FIND_TEMPLATE_BY_ID_FAILURE";
export const FIND_TEMPLATE_BY_BOQ_REQUEST = "FIND_TEMPLATE_BY_BOQ_REQUEST";
export const FIND_TEMPLATE_BY_BOQ_SUCCESS = "FIND_TEMPLATE_BY_BOQ_SUCCESS";
export const FIND_TEMPLATE_BY_BOQ_FAILURE = "FIND_TEMPLATE_BY_BOQ_FAILURE";
export const FIND_ALL_TEMPLATES_REQUEST = "FIND_ALL_TEMPLATES_REQUEST";
export const FIND_ALL_TEMPLATES_SUCCESS = "FIND_ALL_TEMPLATES_SUCCESS";
export const FIND_ALL_TEMPLATES_FAILURE = "FIND_ALL_TEMPLATES_FAILURE";
export const UPDATE_TEMPLATE_REQUEST = "UPDATE_TEMPLATE_REQUEST";
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS";
export const UPDATE_TEMPLATE_FAILURE = "UPDATE_TEMPLATE_FAILURE";
export const DELETE_TEMPLATE_REQUEST = "DELETE_TEMPLATE_REQUEST";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_FAILURE = "DELETE_TEMPLATE_FAILURE";
export const DELETE_TEMPLATE_PERMANENTLY_REQUEST =
  "DELETE_TEMPLATE_PERMANENTLY_REQUEST";
export const DELETE_TEMPLATE_PERMANENTLY_SUCCESS =
  "DELETE_TEMPLATE_PERMANENTLY_SUCCESS";
export const DELETE_TEMPLATE_PERMANENTLY_FAILURE =
  "DELETE_TEMPLATE_PERMANENTLY_FAILURE";
