// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_BOM_REQUEST = "INSERT_BOM_REQUEST";
export const INSERT_BOM_SUCCESS = "INSERT_BOM_SUCCESS";
export const INSERT_BOM_FAILURE = "INSERT_BOM_FAILURE";
export const FIND_BOM_BY_ID_REQUEST = "FIND_BOM_BY_ID_REQUEST";
export const FIND_BOM_BY_ID_SUCCESS = "FIND_BOM_BY_ID_SUCCESS";
export const FIND_BOM_BY_ID_FAILURE = "FIND_BOM_BY_ID_FAILURE";
export const FIND_BOM_BY_BOMID_REQUEST = "FIND_BOM_BY_BOMID_REQUEST";
export const FIND_BOM_BY_BOMID_SUCCESS = "FIND_BOM_BY_BOMID_SUCCESS";
export const FIND_BOM_BY_BOMID_FAILURE = "FIND_BOM_BY_BOMID_FAILURE";
export const FIND_ALL_BOMS_REQUEST = "FIND_ALL_BOMS_REQUEST";
export const FIND_ALL_BOMS_SUCCESS = "FIND_ALL_BOMS_SUCCESS";
export const FIND_ALL_BOMS_FAILURE = "FIND_ALL_BOMS_FAILURE";
export const UPDATE_BOM_REQUEST = "UPDATE_BOM_REQUEST";
export const UPDATE_BOM_SUCCESS = "UPDATE_BOM_SUCCESS";
export const UPDATE_BOM_FAILURE = "UPDATE_BOM_FAILURE";
export const DELETE_BOM_REQUEST = "DELETE_BOM_REQUEST";
export const DELETE_BOM_SUCCESS = "DELETE_BOM_SUCCESS";
export const DELETE_BOM_FAILURE = "DELETE_BOM_FAILURE";
export const DELETE_BOM_PERMANENTLY_REQUEST = "DELETE_BOM_PERMANENTLY_REQUEST";
export const DELETE_BOM_PERMANENTLY_SUCCESS = "DELETE_BOM_PERMANENTLY_SUCCESS";
export const DELETE_BOM_PERMANENTLY_FAILURE = "DELETE_BOM_PERMANENTLY_FAILURE";
export const BOQ_TO_BOM_REQUEST = "BOQ_TO_BOM_REQUEST";
export const BOQ_TO_BOM_SUCCESS = "BOQ_TO_BOM_SUCCESS";
export const BOQ_TO_BOM_FAILURE = "BOQ_TO_BOM_FAILURE";
