// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_SUB_WORK_SUCCESS = "INSERT_SUB_WORK_SUCCESS";
export const INSERT_SUB_WORK_REQUEST = "INSERT_SUB_WORK_REQUEST";
export const INSERT_SUB_WORK_FAILURE = "INSERT_SUB_WORK_FAILURE";
export const FIND_SUB_WORK_BY_ID_REQUEST = "FIND_SUB_WORK_BY_ID_REQUEST";
export const FIND_SUB_WORK_BY_ID_SUCCESS = "FIND_SUB_WORK_BY_ID_SUCCESS";
export const FIND_SUB_WORK_BY_ID_FAILURE = "FIND_SUB_WORK_BY_ID_FAILURE";
export const FIND_ALL_SUB_WORKS_REQUEST = "FIND_ALL_SUB_WORKS_REQUEST";
export const FIND_ALL_SUB_WORKS_SUCCESS = "FIND_ALL_SUB_WORKS_SUCCESS";
export const FIND_ALL_SUB_WORKS_FAILURE = "FIND_ALL_SUB_WORKS_FAILURE";
export const FIND_SUB_WORK_BY_NAME_REQUEST = "FIND_SUB_WORK_BY_NAME_REQUEST";
export const FIND_SUB_WORK_BY_NAME_SUCCESS = "FIND_SUB_WORK_BY_NAME_SUCCESS";
export const FIND_SUB_WORK_BY_NAME_FAILURE = "FIND_SUB_WORK_BY_NAME_FAILURE";
export const UPDATE_SUB_WORK_REQUEST = "UPDATE_SUB_WORK_REQUEST";
export const UPDATE_SUB_WORK_SUCCESS = "UPDATE_SUB_WORK_SUCCESS";
export const UPDATE_SUB_WORK_FAILURE = "UPDATE_SUB_WORK_FAILURE";
export const DELETE_SUB_WORK_REQUEST = "DELETE_SUB_WORK_REQUEST";
export const DELETE_SUB_WORK_SUCCESS = "DELETE_SUB_WORK_SUCCESS";
export const DELETE_SUB_WORK_FAILURE = "DELETE_SUB_WORK_FAILURE";
export const DELETE_SUB_WORK_PERMANENTLY_REQUEST =
  "DELETE_SUB_WORK_PERMANENTLY_REQUEST";
export const DELETE_SUB_WORK_PERMANENTLY_SUCCESS =
  "DELETE_SUB_WORK_PERMANENTLY_SUCCESS";
export const DELETE_SUB_WORK_PERMANENTLY_FAILURE =
  "DELETE_SUB_WORK_PERMANENTLY_FAILURE";
