// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_VENDOR_REQUEST = "INSERT_VENDOR_REQUEST";
export const INSERT_VENDOR_SUCCESS = "INSERT_VENDOR_SUCCESS";
export const INSERT_VENDOR_FAILURE = "INSERT_VENDOR_FAILURE";
export const FIND_VENDOR_BY_ID_REQUEST = "FIND_VENDOR_BY_ID_REQUEST";
export const FIND_VENDOR_BY_ID_SUCCESS = "FIND_VENDOR_BY_ID_SUCCESS";
export const FIND_VENDOR_BY_ID_FAILURE = "FIND_VENDOR_BY_ID_FAILURE";
export const FIND_ALL_VENDORS_REQUEST = "FIND_ALL_VENDORS_REQUEST";
export const FIND_ALL_VENDORS_SUCCESS = "FIND_ALL_VENDORS_SUCCESS";
export const FIND_ALL_VENDORS_FAILURE = "FIND_ALL_VENDORS_FAILURE";
export const UPDATE_VENDOR_REQUEST = "UPDATE_VENDOR_REQUEST";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_VENDOR_FAILURE = "UPDATE_VENDOR_FAILURE";
export const DELETE_VENDOR_REQUEST = "DELETE_VENDOR_REQUEST";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
export const DELETE_VENDOR_FAILURE = "DELETE_VENDOR_FAILURE";
export const DELETE_VENDOR_PERMANENTLY_REQUEST =
  "DELETE_VENDOR_PERMANENTLY_REQUEST";
export const DELETE_VENDOR_PERMANENTLY_SUCCESS =
  "DELETE_VENDOR_PERMANENTLY_SUCCESS";
export const DELETE_VENDOR_PERMANENTLY_FAILURE =
  "DELETE_VENDOR_PERMANENTLY_FAILURE";
