// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_ITEM_REQUEST = "INSERT_ITEM_REQUEST";
export const INSERT_ITEM_SUCCESS = "INSERT_ITEM_SUCCESS";
export const INSERT_ITEM_FAILURE = "INSERT_ITEM_FAILURE";
export const FIND_ITEM_BY_ID_REQUEST = "FIND_ITEM_BY_ID_REQUEST";
export const FIND_ITEM_BY_ID_SUCCESS = "FIND_ITEM_BY_ID_SUCCESS";
export const FIND_ITEM_BY_ID_FAILURE = "FIND_ITEM_BY_ID_FAILURE";
export const FIND_ALL_ITEMS_REQUEST = "FIND_ALL_ITEMS_REQUEST";
export const FIND_ALL_ITEMS_SUCCESS = "FIND_ALL_ITEMS_SUCCESS";
export const FIND_ALL_ITEMS_FAILURE = "FIND_ALL_ITEMS_FAILURE";
export const FIND_ITEM_BY_NAME_REQUEST = "FIND_ITEM_BY_NAME_REQUEST";
export const FIND_ITEM_BY_NAME_SUCCESS = "FIND_ITEM_BY_NAME_SUCCESS";
export const FIND_ITEM_BY_NAME_FAILURE = "FIND_ITEM_BY_NAME_FAILURE";
export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";
export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";
export const DELETE_ITEM_PERMANENTLY_REQUEST =
  "DELETE_ITEM_PERMANENTLY_REQUEST";
export const DELETE_ITEM_PERMANENTLY_SUCCESS =
  "DELETE_ITEM_PERMANENTLY_SUCCESS";
export const DELETE_ITEM_PERMANENTLY_FAILURE =
  "DELETE_ITEM_PERMANENTLY_FAILURE";
