// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_CONTACT_REQUEST = "INSERT_CONTACT_REQUEST";
export const INSERT_CONTACT_SUCCESS = "INSERT_CONTACT_SUCCESS";
export const INSERT_CONTACT_FAILURE = "INSERT_CONTACT_FAILURE";
export const FIND_CONTACT_BY_ID_REQUEST = "FIND_CONTACT_BY_ID_REQUEST";
export const FIND_CONTACT_BY_ID_SUCCESS = "FIND_CONTACT_BY_ID_SUCCESS";
export const FIND_CONTACT_BY_ID_FAILURE = "FIND_CONTACT_BY_ID_FAILURE";
export const FIND_ALL_CONTACTS_REQUEST = "FIND_ALL_CONTACTS_REQUEST";
export const FIND_ALL_CONTACTS_SUCCESS = "FIND_ALL_CONTACTS_SUCCESS";
export const FIND_ALL_CONTACTS_FAILURE = "FIND_ALL_CONTACTS_FAILURE";
export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE";
export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";
export const DELETE_CONTACT_PERMANENTLY_REQUEST =
  "DELETE_CONTACT_PERMANENTLY_REQUEST";
export const DELETE_CONTACT_PERMANENTLY_SUCCESS =
  "DELETE_CONTACT_PERMANENTLY_SUCCESS";
export const DELETE_CONTACT_PERMANENTLY_FAILURE =
  "DELETE_CONTACT_PERMANENTLY_FAILURE";
