// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_UNIT_SUCCESS = "INSERT_UNIT_SUCCESS";
export const INSERT_UNIT_REQUEST = "INSERT_UNIT_REQUEST";
export const INSERT_UNIT_FAILURE = "INSERT_UNIT_FAILURE";
export const FIND_UNIT_BY_ID_REQUEST = "FIND_UNIT_BY_ID_REQUEST";
export const FIND_UNIT_BY_ID_SUCCESS = "FIND_UNIT_BY_ID_SUCCESS";
export const FIND_UNIT_BY_ID_FAILURE = "FIND_UNIT_BY_ID_FAILURE";
export const FIND_ALL_UNITS_REQUEST = "FIND_ALL_UNITS_REQUEST";
export const FIND_ALL_UNITS_SUCCESS = "FIND_ALL_UNITS_SUCCESS";
export const FIND_ALL_UNITS_FAILURE = "FIND_ALL_UNITS_FAILURE";
export const FIND_UNIT_BY_NAME_REQUEST = "FIND_UNIT_BY_NAME_REQUEST";
export const FIND_UNIT_BY_NAME_SUCCESS = "FIND_UNIT_BY_NAME_SUCCESS";
export const FIND_UNIT_BY_NAME_FAILURE = "FIND_UNIT_BY_NAME_FAILURE";
export const UPDATE_UNIT_REQUEST = "UPDATE_UNIT_REQUEST";
export const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS";
export const UPDATE_UNIT_FAILURE = "UPDATE_UNIT_FAILURE";
export const DELETE_UNIT_REQUEST = "DELETE_UNIT_REQUEST";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE";
export const DELETE_UNIT_PERMANENTLY_REQUEST =
  "DELETE_UNIT_PERMANENTLY_REQUEST";
export const DELETE_UNIT_PERMANENTLY_SUCCESS =
  "DELETE_UNIT_PERMANENTLY_SUCCESS";
export const DELETE_UNIT_PERMANENTLY_FAILURE =
  "DELETE_UNIT_PERMANENTLY_FAILURE";
