// Author: Ashutosh Rao Chawan & Suggala Manasvi

export const INSERT_USER_SUCCESS = "INSERT_USER_SUCCESS";
export const INSERT_USER_REQUEST = "INSERT_USER_REQUEST";
export const INSERT_USER_FAILURE = "INSERT_USER_FAILURE";
export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST";
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const FIND_USER_BY_ID_FAILURE = "FIND_USER_BY_ID_FAILURE";
export const FIND_ALL_USERS_REQUEST = "FIND_ALL_USERS_REQUEST";
export const FIND_ALL_USERS_SUCCESS = "FIND_ALL_USERS_SUCCESS";
export const FIND_ALL_USERS_FAILURE = "FIND_ALL_USERS_FAILURE";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_PERMANENTLY_REQUEST =
  "DELETE_USER_PERMANENTLY_REQUEST";
export const DELETE_USER_PERMANENTLY_SUCCESS =
  "DELETE_USER_PERMANENTLY_SUCCESS";
export const DELETE_USER_PERMANENTLY_FAILURE =
  "DELETE_USER_PERMANENTLY_FAILURE";
export const SIGN_IN_USER_REQUEST = "SIGN_IN_USER_REQUEST";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAILURE = "SIGN_IN_USER_FAILURE";
